name: Basic CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test basic functionality
      run: |
        python -c "import fastapi; print('FastAPI version:', fastapi.__version__)"
        python -c "import uvicorn; print('Uvicorn imported successfully')"
        python -c "import sqlalchemy; print('SQLAlchemy version:', sqlalchemy.__version__)"
        python -c "import pydantic; print('Pydantic version:', pydantic.__version__)"
    
    - name: Show project structure
      run: |
        echo "Project files:"
        ls -la
        echo "Python files:"
        find . -name "*.py" | head -5
